### ISSUE TITLE
Add support for new ticker mode. QuoteWithTopOffer

### ISSUE THREAD

**Issue by sivamgr** [zerodha/gokiteconnect#76] opened 2021-12-11 01:47 UTC
Ticker-Quote Mode is without Marketdepth and takes 64 bytes on wire
Ticker-Full Mode is with Marketdepth and takes 184 bytes on wire

Please add support for new ticker mode. QuoteWithTopOffer. In this mode, rather than 5 levels of depth, **1 level of depth shall be provided.**

**Ticker-QuoteWithTopOffer shall provide Best Bid, Besk Ask along with the Quote data.** This only needs 20-24 bytes inaddition to Quote mode. 84 bytes(with no padding) - 88 bytes (with padding)

With this feature available for usecases needing only the top bid/asks, application need not to choose subscribing full-depths and help with reducing the network-streaming traffic by 50%

**Comment by rhnvrm** [comment] 2021-12-12 08:37
Closing as duplicate of https://github.com/zerodha/pykiteconnect/issues/142

**Closed by rhnvrm** 2021-12-12 08:37 UTC
